## Add your compose file here
services:
  mc-discord-bot:
    build: .
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - MINECRAFT_IP=${MINECRAFT_IP}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - COMMAND_PREFIX=${COMMAND_PREFIX:-!}
      - TOGGLE_ROLE_ID=${TOGGLE_ROLE_ID:-0}
    volumes:
      - bot_data:/app/data

volumes:
  bot_data: {}
